version: "3"
services:
  app:
    build:
      context: .
      dockerfile: $PWD/api/Dockerfile
    ports:
      - 5000:5000
    tty: true
    volumes:
      - $PWD/api:/app
      - $PWD/script:/script
      - $PWD/web:/web
    env_file:
      - $PWD/.env
    working_dir: /app
    networks:
      - default
    command:
      - pipenv
      - run
      - python
      - __init__.py
  serveo_app:
    image: node:latest
    volumes: 
      - $PWD:/app
    working_dir: /app
    environment:
      - SUBDOMAIN=ahfargoapp
      - CONTAINER=app
      - PORT=5000
    networks:
      - default
    command:
      - bash
      - script/serveo.sh
  web:
    image: httpd:2.4
    ports:
      - 5100:80
    volumes:
      - $PWD/web:/usr/local/apache2/htdocs/
    networks:
      - default
  serveo_web:
    image: node:latest
    volumes: 
      - $PWD:/app
    working_dir: /app
    environment:
      - SUBDOMAIN=ahfargoweb
      - CONTAINER=web
      - PORT=80
    networks:
      - default
    command:
      - bash
      - script/serveo.sh