version: "3"
services:
  app:
    build: ./api
    tty: true
    networks: 
      - default
    ports:
      - 5010:8090
    volumes: 
      - ./api:/app
    working_dir: /app
    command:
      - pipenv
      - run
      - python
      - manage.py
      - runserver
      - 0.0.0.0:8090
  web:
    image: node:latest
    tty: true
    env_file:
      - .env
    networks: 
      - default
    ports:
      - 5110:8080
    volumes: 
      - ./web:/web
    working_dir: /web
    command:
      - npm
      - run
      - serve