"""
Django settings for app project.

Generated by 'django-admin startproject' using Django 2.1.

For more information on this file, see
https://docs.djangoproject.com/en/2.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.1/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'iovl-clm*ken@m2*)+t__zm#uisml7w2o%7($@)(^+7@b(kw9-'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
]

ROOT_URLCONF = 'app.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'app.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/2.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.1/howto/static-files/

STATIC_URL = '/static/'

# Custom setting

CORS_ORIGIN_ALLOW_ALL = True

ALLOWED_HOSTS = [
    '*',  # For dev
]

PTX_ID = 'ad64f3b34d38425ca0bb7efdcdb4548b'

PTX_KEY = 'wabKRdVqcFg4i5CqLXP4JuWQ3Ws'

# GLOBAL = {
#     "FILE_ROUTE": '%s/' % os.path.dirname(os.path.abspath(__file__)),
#     "LINE_TOKEN": 'vZwZvgmlljz+VfSYn6Khu2RXQM8Gq3gkODZD8tdHEYgcxsUCI3rHSgh3CO3d7xmXvZ8irnEBQxm1Wughpaj+u1qANpzBavf3VTczraBo+VE4n4QaQpuhGwro/4wMXS1Zde+CyZ0d2Bxk55ZQG4MZBAdB04t89/1O/w1cDnyilFU=',
#     "LINE_SECRET": 'c56fe3888c3cfe60a1969fdd19c9b10c',
#     "APP_ID": 'ad64f3b34d38425ca0bb7efdcdb4548b',
#     "APP_KEY": 'wabKRdVqcFg4i5CqLXP4JuWQ3Ws',
#     "GOOGLE_MAP_KEY": 'AIzaSyCUx_og-8aUvdj5jDYyQGALwnzlQw_jXok',
#     "IMAGE_URL": "https://worldcrater.com/Ahfargo_bus_bot_image/",
#     "RICH_FUNC": "richmenu-ce2919554f6ff106c075bef379923fab",
#     "RICH_INFO": "richmenu-f6ce6b077ffd608b59845bbf2fabd3be",
#     "LIFF_BUS": "line://app/1586634703-dLEbzgxb",
#     "LIFF_BIKE": "line://app/1586634703-MqWqnV6q",
#     "LIFF_GMAP": "line://app/1586634703-krVJolxJ",
#     "VIDEO_IMAGE": "https://i.imgur.com/KA7yZnl.png",
#     "LOCATION_MENU": "https://i.imgur.com/iEHFhIg.png",
#     "LOCATION_ICON": "https://i.imgur.com/ZZLbNkM.png"
# }