version: "3"
services:
  app:
    build: .
    tty: true
    ports:
      - 8090:8000
    volumes: 
      - .:/app
    working_dir: /app
    command:
      - pipenv
      - run
      - python
      - manage.py
      - runserver
      - 0.0.0.0:8000