version: "3"
services:
  web:
    image: node:latest
    tty: true
    ports:
      - 8080:8080
    env_file:
      - ./.env
    volumes:
      - .:/app
    working_dir: /app
    command:
      - npm
      - run
      - serve